 name: gitartwork from a contribution graph
 on: 
   push:
   schedule:
     - cron: '* */24 * * *'
   workflow_dispatch:
 jobs:
   build:
     name: Make gitartwork SVG
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
         with:
          repo: shentuzhigang/shentuzhigang.github.io
          ref: gh-pages
       - uses: jasineri/gitartwork@v1
         with:
            # Use this username's contribution graph  
            user_name: shentuzhigang
            # Text on contribution graph 
            text: Starzkg
       # 查看 workflow 的文档来获取更多信息
       # @see https://github.com/crazy-max/ghaction-github-pages
       - name: Deploy to GitHub Pages
         uses: crazy-max/ghaction-github-pages@v2.5.0
         with:
           # 部署到指定仓库
           repo: shentuzhigang/shentuzhigang.github.io
           # 部署到 gh-pages 分支
           target_branch: gh-pages
           # 部署目录为 VuePress 的默认输出目录
           build_dir: .
           keep_history: false
         env:
           # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
           GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
